blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="blog-home"),
    path("about/", views.about, name="blog-about"),
    path("create-post/", views.create_post, name="create_post"),
    path("update-post/<int:pk>/", views.update_post, name="update_post"),
    path("detail/<int:pk>/", views.post_detail, name="detail"),
    path("like", views.like_a_post, name="like"),
    path("comment", views.add_comment, name="comment")
]

django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.static import serve
from django.urls import re_path
from django.conf import settings

from users import views as user_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("profile/", user_views.profile, name="profile"),
    path("profile/<str:username>", user_views.user_profile, name="user_profile"),
    path("register/", user_views.register, name="register"),
    path("update-user/", user_views.update_user, name="update_user"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path("", include("blog.urls")),
]

if not settings.DEBUG:
    # deployment fix to server media files
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve,{
            'document_root': settings.MEDIA_ROOT,
        })
    ]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT,
    )

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    
class Comments(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.content

class Like(models.Model):
    post = models.OneToOneField(Post, on_delete=models.CASCADE)
    number = models.IntegerField(default=0)
    
    def __str__(self):
        return self.post.title

blog/forms.py
from django import forms

from .models import Post, Comments


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content"]
        widgets = {
      'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your blog title'}),
      'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10, 'placeholder': 'Write your blog content here'}),
    }
        
class PostComment(forms.ModelForm):
    class Meta:
        model = Comments
        labels = {"content": ""}
        fields = ["content"]
        widgets = {
      'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 4, 'placeholder': 'Write your comment here'}),
    }
    

blog/views.py
from django.contrib import messages
from django.http import HttpRequest, JsonResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PostForm, PostComment
from .models import Post, Like, Comments
import json


def home(request):
    posts = Post.objects.all().order_by("-date_posted")
    context = {"posts": posts}
    return render(request, "blog/home.html", context)


def add_comment(request: HttpRequest):
    comment_form = PostComment(request.POST)
    if comment_form.is_valid():
        content = comment_form.cleaned_data["content"]
        post_id = request.POST.get("post")
        try:
            post = Post.objects.get(pk=post_id)
            comment = Comments(
            content=content,
            user=request.user,
            post=post
            )
            comment.save()
            return redirect("detail", pk=comment.post.pk)
        except:
            messages.error(request, "Post not found")
            return redirect("blog-home")

def like_a_post(request: HttpRequest):
    if request.user.is_authenticated and request.method == "POST":
        body_d = json.loads(request.body.decode("utf-8"))
        post_id = body_d["post_id"]
        post = Post.objects.get(pk=post_id)
        post.like.number += 1
        post.like.save()
        current_likes = post.like.number
        return JsonResponse({"likes": current_likes})
    return JsonResponse({"error": "Must be logged in to like a post"})


def about(request):
    return render(request, "blog/about.html", {"title": "About"})


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comment_form = PostComment()
    context = {"post": post, "request": request, "comment_form": comment_form}
    return render(request, "blog/post_detail.html", context)


def update_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        if request.user == post.author or request.user.is_superuser:
            form = PostForm(request.POST, instance=post)
            if form.is_valid():
                user = form.save(commit=False)
                user.save()
                messages.success(request, "The post has been updated successfully.")
                return redirect("blog-home")
            else:
                messages.error(request, "Please correct the following errors:")
        messages.error(request, "You are not authorized to update this post.")
    else:
        form = PostForm(instance=post)
    return render(request, "blog/create_post.html", {"form": form, "type": "Update"})


@login_required
def create_post(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.author = request.user
            user.save()
            messages.success(request, "The post has been created successfully.")
            return redirect("blog-home")
        else:
            messages.error(request, "Please correct the following errors:")
    else:
        form = PostForm()
    return render(request, "blog/create_post.html", {"form": form, "type": "Create"})

blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block content %}
<div class="container">
    <h1 class="display-4" style="font-family: 'Inria Sans', sans-serif; font-weight: 700;">Django Blogs</h1>
    <p class="lead">A Simple Blogging Platform</p>
    <hr class="my-4">
    <div class="row">
        <div class="col-md-6">
            <h2>What is Django Blogs?</h2>
            <p>
                Django Blogs is a simple and lightweight blogging application built with Django.
                It allows users to register and create their own blogs where they can write short and informative posts.
            </p>
        </div>
        <div class="col-md-6">
            <h2>Getting Started</h2>
            <p>
                To start using Django Blogs, simply register for an account and create your own blog.
                You can then write and publish blog posts on any topic that interests you.
                The application provides a user-friendly interface for creating and managing your blog content.
            </p>
        </div>
    </div>
</div>
<div class="card mt-4">
    <div class="card-body">
        <h5 class="card-title">Developers Note</h5>
        <p class="card-text">Django Blogs is an open-source project. We welcome contributions from the community! If
            you're interested in helping out, you can:</p>
        <ul>
            <li>Contribute to the project on GitHub: github.com/gh0stfkr </li>
            <li>Help keep the project running by donating: twitter.com/gh0stfrk </li>
        </ul>
    </div>
</div>
{% endblock content %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link
    href="https://fonts.googleapis.com/css2?family=Inria+Sans:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap"
    rel="stylesheet">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  {% if title %}
  <title>Django Blogs - {{ title }}</title>
  {% else %}
  <title>Django Blogs</title>
  {% endif %}
  <link rel="shortcut icon" href="{% static 'icon.png' %}" type="image/x-icon" class=" filter: invert(100%);">
  {% block head %} {% endblock %}
</head>

<body style="font-family: 'Inria Sans', sans-serif;">
  <nav class="navbar navbar-light bg-light navbar-expand-lg p-4">
    <a class="navbar-brand fw-bold" style="font-family: 'Inria Sans', sans-serif; font-weight: 700;" href="{% url 'blog-home' %}">
      DjangoBlogs
    </a>
    <button class="navbar-toggler btn-outline-none border-none" type="button" data-toggle="collapse"
      data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon dark"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'blog-home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog-about' %}">About</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'profile' %}">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'create_post' %}">Post</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}">Register</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>
  <main role="main" class="container">
    <div class="row">
      <div class="col-md-8 p-4">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
        {% endif %}
        {% block content %}{% endblock %}
      </div>
      <div class="col-md-4 p-4">
        <div class="content-section">
          <h3>Contact Information</h3>
          <p class='text-muted'>
          <ul class="list-group">
            <li class="list-group-item list-group-item-light">
              <a href="https://github.com/gh0stfrk" target="_blank">Github</a>
            </li>
            <li class="list-group-item list-group-item-light">
              <a href="https://twitter.com/gh0stfrk" target="_blank">Twitter</a>
            </li>
          </ul>
          </p>
        </div>
      </div>
    </div>
  </main>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/create_post.html
{% extends "blog/base.html" %}

{% block content %}
    <h1>{{ type }} Post</h1>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-primary">{{ type }}</button>
    </form>
{% endblock content %}

blog/templates/blog/home.html
{% extends "blog/base.html" %}

{% load static %}
{% load cloudinary %}

{% block content %}

{% for post in posts %}
<article class="media content-section border mt-2 rounded p-2">
  <div class="media-body">
    <div class="article-metadata p-1 mb-2">
      <img class="rounded-circle" style="aspect-ratio: 1/1; width: 40px;" src="{{ post.author.profile.image.url }}"
        alt="profile_photo">
      @{{ post.author }}
      <small class="text-muted">{{ post.date_posted | date:"F d, Y" }}</small>
    </div>
    <a class="p-2" href="{% url 'detail' post.id %}">{{ post.title }}</a>
    <p class="p-2">{{ post.content }}</p>
    <div class="interactions">
      <div class="likes d-flex flex-col justify-items-center align-items-baseline p-2" style="gap: 1rem;">
        <button class="like-button btn btn-primary btn-sm" data-post-id="{{ post.id }}">Like</button>
        <p id="like-count{{post.id}}">{{ post.like.number }}</p>
      </div>
    </div>
  </div>
</article>
{% endfor %}
<script>
  const likeButtons = document.querySelectorAll('.like-button');

  const csrfToken = '{{ csrf_token }}';

  likeButtons.forEach((button) => {
    const postId = button.dataset.postId;
    button.addEventListener('click', () => {
      fetch(
        "/like",
        {
          "method": "POST",
          body: JSON.stringify({
            "post_id": postId
          }),
          headers: {
            'X-CSRFToken': csrfToken
          }
        },
      ).then(response => {
        if (!response.ok) {
          alert("something went wrong")
        }
        return response.json()
      }).then(data => {
        const likeCount = document.getElementById('like-count' + postId);
        if (data.likes) {
          likeCount.textContent = data.likes
        }
        button.disabled = true
      })
    })

  })
</script>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}

<article class="media content-section border rounded p-2">
  <div class="media-body">
    <div class="article-metadata p-2">
      <img class="rounded-circle" src="{{ post.author.profile.image.url }}" alt="profile_photo"
        style="aspect-ratio: 1/1; width: 50px;">
      <a class="mr-2" href="#">{{ post.author }}</a>
      <small class="text-muted">{{ post.date_posted | date:"F d, Y" }}</small>
      {% if request.user.id == post.author.id %}
      <a href="{% url 'update_post' pk=post.id %}" class="btn btn-primary ml-2 btn-sm">Update</a>
      {% elif request.user.is_superuser %}
      <a href="{% url 'update_post' pk=post.id %}" class="btn btn-danger ml-2 btn-sm">Update</a>
      {% endif %}
    </div>
    <h2 class="p-2">{{ post.title }}</h2>
    <p class="article-content p-2">{{ post.content }}</p>
    <div class="interactions">
      <div class="likes d-flex flex-col justify-items-center align-items-baseline p-2" style="gap: 1rem;">
        <button class="like-button btn btn-primary btn-sm" data-post-id="{{ post.id }}">Like</button>
        <p id="like-count">{{ post.like.number }}</p>
      </div>
    </div>
    <div class="comments">
      {% if request.user.is_authenticated %}
      <div class="add-comment">
        <form action="{% url 'comment' %}" method="post" style="gap: 1rem;">
          {% csrf_token %}
          <div>
            <img class="rounded-circle m-2" src="{{ request.user.profile.image.url }}" alt="profile_photo"
            style="aspect-ratio: 1/1; width: 40px;">
            <p class="d-inline text-muted">@{{ request.user.username }}</p>
          </div>
        {{ comment_form.as_p }}
        <input type="hidden" name="post" id="post" value="{{ post.id }}">
        <input type="submit" value="Comment" class="btn btn-primary btn-sm">
        </form>
      </div>
      {% else %}
      <div class="text-muted">Login to add comments</div>
      {% endif %}
      <!-- Comments render below -->
      <div class="mt-2 p-2">
        <h2>Comments</h2>
        {% for comment in post.comments_set.all %}
        <div class="p-2 mt-2">
          <img class="rounded-circle" src="{{ comment.user.profile.image.url }}" alt="profile_photo"
          style="aspect-ratio: 1/1; width: 40px;">
          {{ comment.user.username }}
          <small class="text-muted">{{ comment.date_posted | date:"F d, Y" }}</small>
          <div class="mt-2">
            {{ comment.content }}
          </div>
        </div>
        {% endfor %}
      </div>

    </div>
  </div>
</article>

<script>
  const button = document.querySelector('.like-button');
  const csrfToken = '{{ csrf_token }}';
  const postId = button.dataset.postId;

  button.addEventListener('click', () => {
    fetch(
      "/like",
      {
        "method": "POST",
        body: JSON.stringify({
          "post_id": postId
        }),
        headers: {
          'X-CSRFToken': csrfToken
        }
      },
    ).then(response => {
      if (!response.ok) {
        alert("something went wrong")
      }
      return response.json()
    }).then(data => {
      const likeCount = document.getElementById('like-count');
      if (data.likes){
        likeCount.textContent = data.likes
      }
      button.disabled = true
    })
  })

</script>
{% endblock %}